name: doppio_utils_config
description: A new Flutter package project.
version: 0.0.5
homepage: https://github.com/doppio-dev/utils

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pubspec_yaml: 3.1.0
  plain_optional: 1.0.0
  yaml: 3.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.11.1
